name: "Pull Request Jobs"

on:
  pull_request:
  workflow_dispatch:

env:
  tf_version: 1.9.8
  working_dir: .

jobs:
  terraform-doc-generation:
    permissions:
      contents: "write"
      id-token: "write"
      pull-requests: "write"
      issues: "write"
    name: "Terraform Documentation Generation"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Check Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          find-dir: modules/
          recursive: true
          recursive-path: .
          git-push: true
          output-method: replace
          template: "{{ .Content }}"

      # recurse every directory in the ./modules directory
      # and run the terraform test command
      - name: Run Terraform Unit Tests
        run: |
          for dir in $(find ${{env.working_dir}}/modules -type d -not -path '*/\.terraform/*'); do
            echo "Running tests in $dir"
            cd $dir
            terraform init
            terraform test
            cd -
          done
